import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useCampus } from '@/context/CampusContext';
import { useAuth } from '@/context/AuthContext';
import { z } from 'zod';

// Validation schema
const createTokenSchema = z.object({
  amount: z.number().positive('Amount must be positive').max(10000, 'Amount too high'),
});

interface PrepaidToken {
  id: string;
  campus_id: string;
  user_id: string;
  token_number: string;
  amount: number;
  qr_code: string;
  is_used: boolean;
  payment_status: string;
  customer_name: string | null;
  customer_email: string | null;
  created_at: string;
  used_at: string | null;
}

// Fetch user's prepaid tokens
export function usePrepaidTokens() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['prepaid-tokens', user?.id],
    queryFn: async () => {
      if (!user?.id) return [];

      const { data, error } = await supabase
        .from('prepaid_tokens')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return (data || []) as PrepaidToken[];
    },
    enabled: !!user?.id,
  });
}

// Fetch admin view of campus prepaid tokens
export function useAdminPrepaidTokens() {
  const { campus } = useCampus();

  return useQuery({
    queryKey: ['admin-prepaid-tokens', campus?.id],
    queryFn: async () => {
      if (!campus?.id) return [];

      const { data, error } = await supabase
        .from('prepaid_tokens')
        .select('*')
        .eq('campus_id', campus.id)
        .order('created_at', { ascending: false })
        .limit(100);

      if (error) throw error;
      return (data || []) as PrepaidToken[];
    },
    enabled: !!campus?.id,
    refetchInterval: 5000, // Auto-refresh for real-time updates
  });
}

// Create a new prepaid token
export function useCreatePrepaidToken() {
  const queryClient = useQueryClient();
  const { campus } = useCampus();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (input: { amount: number }) => {
      if (!campus?.id) throw new Error('No campus selected');
      if (!user?.id) throw new Error('Not authenticated');

      // Validate input
      const validationResult = createTokenSchema.safeParse(input);
      if (!validationResult.success) {
        throw new Error(validationResult.error.errors[0]?.message || 'Invalid amount');
      }

      const { data, error } = await supabase
        .from('prepaid_tokens')
        .insert([{
          campus_id: campus.id,
          user_id: user.id,
          amount: validationResult.data.amount,
          customer_name: user.fullName || null,
          customer_email: user.email || null,
          payment_status: 'pending',
          // These will be auto-generated by the database trigger
          token_number: 'GENERATING',
          qr_code: 'GENERATING',
        }])
        .select()
        .single();

      if (error) throw error;
      return data as PrepaidToken;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['prepaid-tokens'] });
    },
  });
}

// Update token payment status
export function useUpdateTokenPayment() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: 'completed' | 'failed' }) => {
      const { data, error } = await supabase
        .from('prepaid_tokens')
        .update({ payment_status: status })
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data as PrepaidToken;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['prepaid-tokens'] });
      queryClient.invalidateQueries({ queryKey: ['admin-prepaid-tokens'] });
    },
  });
}

// Mark token as used (admin only)
export function useMarkPrepaidTokenUsed() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      // Validate UUID format
      const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
      if (!uuidRegex.test(id)) {
        throw new Error('Invalid token ID');
      }

      const { data, error } = await supabase
        .from('prepaid_tokens')
        .update({ 
          is_used: true, 
          used_at: new Date().toISOString() 
        })
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data as PrepaidToken;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['prepaid-tokens'] });
      queryClient.invalidateQueries({ queryKey: ['admin-prepaid-tokens'] });
    },
  });
}

// Get token by QR code (for scanning)
export function useGetTokenByQR() {
  return useMutation({
    mutationFn: async (qrCode: string) => {
      // Extract token ID from QR code (format: PREPAID:uuid)
      const match = qrCode.match(/^PREPAID:(.+)$/);
      if (!match) {
        throw new Error('Invalid prepaid token QR code');
      }

      const tokenId = match[1];

      const { data, error } = await supabase
        .from('prepaid_tokens')
        .select('*')
        .eq('id', tokenId)
        .single();

      if (error) throw error;
      return data as PrepaidToken;
    },
  });
}
